FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN mkdir -p /data/simrekap

COPY server/ /app/server/
COPY src/data/ /app/src/data/

EXPOSE 8000

CMD ["python", "server/main.py"]
